Update hostapd
Changed behaviour for multi partitioning support

diff --git a/SDCARD/hostapd b/SDCARD/hostapd
--- a/SDCARD/hostapd
+++ b/SDCARD/hostapd
@@ -1,25 +1,30 @@
 #!/bin/sh
 
 # Export variables for init script
-export hack="/mnt/HACK"
+export hack="/tmp/sd/HACK"
 export hack_conf="$hack/etc/hack.conf"
 export hack_custom_conf="$hack/etc/hack_custom.conf"
 export commands_conf="$hack/etc/commands.conf"
 
 # Custom scripts
-custom_pre_init="/mnt/CUSTOM/pre_init.sh"
-custom_pre_init_async="/mnt/CUSTOM/pre_init_custom.sh"
-export custom_pre_services="/mnt/CUSTOM/pre_services.sh"
-export custom_pre_services_async="/mnt/CUSTOM/pre_services_async.sh"
-export custom_pre_services_once="/mnt/CUSTOM/pre_services_once.sh"
-export custom_pre_services_once_async="/mnt/CUSTOM/pre_services_once_async.sh"
+custom_pre_init="/tmp/sd/CUSTOM/pre_init.sh"
+custom_pre_init_async="/tmp/sd/CUSTOM/pre_init_custom.sh"
+export custom_pre_services="/tmp/sd/CUSTOM/pre_services.sh"
+export custom_pre_services_async="/tmp/sd/CUSTOM/pre_services_async.sh"
+export custom_pre_services_once="/tmp/sd/CUSTOM/pre_services_once.sh"
+export custom_pre_services_once_async="/tmp/sd/CUSTOM/pre_services_once_async.sh"
+
+# SD device and path
+sd_dev="/dev/mmcblk0p2"
+sd_path="/tmp/sd"
 
 # Logging
 hack_log="/tmp/hostapd.log"
 hack_err="/tmp/hostapd.err"
 
 # Hostapd and config 
-hostapd="$hack/sbin/hostapd"
+hostapd="/mnt/hostapd.real"
+hostapd_real="/tmp/hostapd.real"
 hostapd_conf="/mnt/_ht_ap_mode.conf"
 
 # Init script path
@@ -30,7 +35,7 @@ update="$hack/sbin/update.sh"
 
 # Reboot flag
 reboot_flag="/tmp/hostapd.reboot"
-reboot_file="/mnt/hostapd.reboot"
+reboot_file="/tmp/sd/hostapd.reboot"
 
 # Copy shadow and passwd files and clean them in case they were edited in windows
 for i in shadow passwd; do
@@ -51,13 +56,19 @@ if [ -x "$hostapd" -a -f "$hostapd_conf" -a "$1" != "" -a "$2" = "-B" ]; then
 	hostapd_ssid=`cat $hostapd_conf | grep "^ssid"`
 	
 	if [ "$hostapd_ssid" = "" ]; then
-		$hostapd "$1" "$2"
+		cp $hostapd $hostapd_real
+		$hostapd_real "$1" "$2"
 	fi
 else
 	# Remove AP mode file and reset wifi to client mode
 	rm -f /tmp/_ht_ap_mode.conf 
 	killall udhcpd
 	ifconfig wlan0 0.0.0.0
+	
+	# Mmount SD on location that won't be umounted by device
+	echo -n "Mount SD card on seperate location $sd_path..."
+	mkdir -p $sd_path >/dev/null 2>&1
+	mount $sd_dev $sd_path && echo "done" || echo "failed"
 	
 	# Check for updates
 	[ -x $update ] && $update
